- name: install docker-compose & docker
  ansible.builtin.pip:
    name:
      - docker-compose
      - docker

- name: Clone repo
  ansible.builtin.git:
    repo: "{{ git_repository }}"
    dest: "{{ deployment_path }}"
    version: "{{ git_branch }}"

- name: "start docker-compose"
  docker_compose:
    project_src: "{{ deployment_path }}"
    build: yes
    debug: yes
